import type { NextConfig } from "next"

const nextConfig: NextConfig = {
  // exclude generated directory as that was generated by Prisma
  eslint: {
    dirs: ["src/app", "src/lib"]
  }
}

export default nextConfig
